#!/usr/bin/env sh
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

TYPE="${BLOCK_INSTANCE:-mem}"
PERCENT="${PERCENT:-true}"

COLOR_NORMAL="${COLOR_NORMAL:-$color}"
COLOR_WARN="${COLOR_WARN:-#FFFF85}"
COLOR_DANG="${COLOR_DANG:-#FFAE50}"
COLOR_CRIT="${COLOR_CRIT:-#e26a72}"

awk -v type=$TYPE -v percent=$PERCENT \
    -v COLOR_NORMAL=$COLOR_NORMAL -v COLOR_WARN=$COLOR_WARN \
    -v COLOR_DANG=$COLOR_DANG -v COLOR_CRIT=$COLOR_CRIT '
/^MemTotal:/ {
	mem_total=$2
}
/^MemFree:/ {
	mem_free=$2
}
/^Buffers:/ {
	mem_free+=$2
}
/^Cached:/ {
	mem_free+=$2
}
/^SwapTotal:/ {
	swap_total=$2
}
/^SwapFree:/ {
	swap_free=$2
}
END {
	if (type == "swap") {
		free=swap_free/1024/1024
		used=(swap_total-swap_free)/1024/1024
		total=swap_total/1024/1024
	} else {
		free=mem_free/1024/1024
		used=(mem_total-mem_free)/1024/1024
		total=mem_total/1024/1024
	}
	pct=0
	if (total > 0) {
		pct=used/total*100
	}
	# full text
	if (percent == "true" ) {
		printf("%.1fG/%.1fG (%.f%%)\n", used, total, pct)
	} else {
		printf("%.1fG/%.1fG\n", used, total)
	}
	# short text
	printf("%.f%%\n", pct)
	# color
	if (pct > 90) {
		print(COLOR_CRIT)
	} else if (pct > 80) {
		print(COLOR_DANG)
	} else if (pct > 70) {
		print(COLOR_WARN)
  } else {
    print(COLOR_NORMAL)
  }
}
' /proc/meminfo
